version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/pa_crm
      - JWT_SECRET=your_jwt_secret
      - DO_SPACES_KEY=${DO_SPACES_KEY}
      - DO_SPACES_SECRET=${DO_SPACES_SECRET}
      - DO_SPACES_ENDPOINT=${DO_SPACES_ENDPOINT}
      - DO_SPACES_REGION=${DO_SPACES_REGION}
      - DO_SPACES_BUCKET=${DO_SPACES_BUCKET}
      - DO_SPACES_CDN_URL=${DO_SPACES_CDN_URL}
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pa_crm
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 